apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "backstage-demo"
  annotations:
    github.com/project-slug: 'backstage/backstage'
    sentry.io/project-slug: 'YOUR_PROJECT_SLUG'
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
