apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "backstage-demo"
  annotations:
    github.com/project-slug: 'shabbirsaifee92/backstage-demo'
    sentry.io/project-slug: 'YOUR_PROJECT_SLUG'
  tags:
    - nginx
    - nodejs
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
    - url: https://metrics.example-org.com
      title: metrics
      icon: analytics
      type: metrics-dashboard
    - url: https://logs.example-org.com
      title: logs
      icon: assignment
      type: logs-dashboard
spec:
  type: service
  owner: shabbirsaifee92
  lifecycle: experimental
  definition:
    $text: ./backstage.oas.yaml
