apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "backstage-demo"
  annotations:
    github.com/project-slug: 'shabbirsaifee92/backstage-demo'
    sentry.io/project-slug: 'YOUR_PROJECT_SLUG'
spec:
  type: service
  owner: shabbirsaifee92
  lifecycle: experimental
  definition:
    $text: ./backstage.oas.yaml
