name: Demo CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo some statements
        run: |
          echo "Hello, this is a demo CI pipeline!"
          echo "Current date: $(date)"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Commit SHA: $GITHUB_SHA"

      - name: Run a simple test
        run: echo "Test completed successfully!"
